project:
  type: website

website:
  title: "Jorge Mendes"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/jorgelum/Jorge-Mendes
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: yeti
    css: styles.css

editor: visual

comments:
  giscus:
    repo: jorgelum/Jorge-Mendes

