project:
  type: website

website:
  title: "Jorge Mendes"
  site-url: "https://jormendes.com/"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/jorgelum/Jorge-Mendes
      - icon: twitter
        href: https://twitter.com
      - icon: linkedin
        href: https://br.linkedin.com/in/jorge-luiz-mendes-bab690227?trk=people-guest_people_search-card
        
format:
  html:
    theme: lux
    css: styles.css
    smooth-scroll: true
    link-external-icon: false
    link-external-newwindow: true
    link-external-filter: '^(?:http:|https:)\/\/www\.jorgemendes\.com\/**'
    citations-hover: true
    footnotes-hover: true
    toc: true
    code-link: true

    

editor: visual

comments: 
  giscus:
    repo: jorgelum/Jorge-Mendes

